// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "License.pb.h"
// @@protoc_insertion_point(imports)

@implementation FPLicenseRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [FPLicenseRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [ObjectivecDescriptorRoot registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface FPMetadata ()
@property (strong) NSString* name;
@property (strong) NSString* target;
@property (strong) NSString* licenseId;
@property SInt64 created;
@property (strong) NSData* additional;
@end

@implementation FPMetadata

- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) _value_ {
  hasName_ = !!_value_;
}
@synthesize name;
- (BOOL) hasTarget {
  return !!hasTarget_;
}
- (void) setHasTarget:(BOOL) _value_ {
  hasTarget_ = !!_value_;
}
@synthesize target;
- (BOOL) hasLicenseId {
  return !!hasLicenseId_;
}
- (void) setHasLicenseId:(BOOL) _value_ {
  hasLicenseId_ = !!_value_;
}
@synthesize licenseId;
- (BOOL) hasCreated {
  return !!hasCreated_;
}
- (void) setHasCreated:(BOOL) _value_ {
  hasCreated_ = !!_value_;
}
@synthesize created;
- (BOOL) hasAdditional {
  return !!hasAdditional_;
}
- (void) setHasAdditional:(BOOL) _value_ {
  hasAdditional_ = !!_value_;
}
@synthesize additional;
- (instancetype) init {
  if ((self = [super init])) {
    self.name = @"";
    self.target = @"";
    self.licenseId = @"";
    self.created = 0L;
    self.additional = [NSData data];
  }
  return self;
}
static FPMetadata* defaultFPMetadataInstance = nil;
+ (void) initialize {
  if (self == [FPMetadata class]) {
    defaultFPMetadataInstance = [[FPMetadata alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFPMetadataInstance;
}
- (instancetype) defaultInstance {
  return defaultFPMetadataInstance;
}
- (BOOL) isInitialized {
  if (!self.hasName) {
    return NO;
  }
  if (!self.hasTarget) {
    return NO;
  }
  if (!self.hasLicenseId) {
    return NO;
  }
  if (!self.hasCreated) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasName) {
    [output writeString:1 value:self.name];
  }
  if (self.hasTarget) {
    [output writeString:2 value:self.target];
  }
  if (self.hasLicenseId) {
    [output writeString:3 value:self.licenseId];
  }
  if (self.hasCreated) {
    [output writeInt64:4 value:self.created];
  }
  if (self.hasAdditional) {
    [output writeData:5 value:self.additional];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasName) {
    size_ += computeStringSize(1, self.name);
  }
  if (self.hasTarget) {
    size_ += computeStringSize(2, self.target);
  }
  if (self.hasLicenseId) {
    size_ += computeStringSize(3, self.licenseId);
  }
  if (self.hasCreated) {
    size_ += computeInt64Size(4, self.created);
  }
  if (self.hasAdditional) {
    size_ += computeDataSize(5, self.additional);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FPMetadata*) parseFromData:(NSData*) data {
  return (FPMetadata*)[[[FPMetadata builder] mergeFromData:data] build];
}
+ (FPMetadata*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPMetadata*)[[[FPMetadata builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FPMetadata*) parseFromInputStream:(NSInputStream*) input {
  return (FPMetadata*)[[[FPMetadata builder] mergeFromInputStream:input] build];
}
+ (FPMetadata*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPMetadata*)[[[FPMetadata builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FPMetadata*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FPMetadata*)[[[FPMetadata builder] mergeFromCodedInputStream:input] build];
}
+ (FPMetadata*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPMetadata*)[[[FPMetadata builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FPMetadataBuilder*) builder {
  return [[FPMetadataBuilder alloc] init];
}
+ (FPMetadataBuilder*) builderWithPrototype:(FPMetadata*) prototype {
  return [[FPMetadata builder] mergeFrom:prototype];
}
- (FPMetadataBuilder*) builder {
  return [FPMetadata builder];
}
- (FPMetadataBuilder*) toBuilder {
  return [FPMetadata builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  if (self.hasTarget) {
    [output appendFormat:@"%@%@: %@\n", indent, @"target", self.target];
  }
  if (self.hasLicenseId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"licenseId", self.licenseId];
  }
  if (self.hasCreated) {
    [output appendFormat:@"%@%@: %@\n", indent, @"created", [NSNumber numberWithLongLong:self.created]];
  }
  if (self.hasAdditional) {
    [output appendFormat:@"%@%@: %@\n", indent, @"additional", self.additional];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasName) {
    [dictionary setObject: self.name forKey: @"name"];
  }
  if (self.hasTarget) {
    [dictionary setObject: self.target forKey: @"target"];
  }
  if (self.hasLicenseId) {
    [dictionary setObject: self.licenseId forKey: @"licenseId"];
  }
  if (self.hasCreated) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.created] forKey: @"created"];
  }
  if (self.hasAdditional) {
    [dictionary setObject: self.additional forKey: @"additional"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FPMetadata class]]) {
    return NO;
  }
  FPMetadata *otherMessage = other;
  return
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      self.hasTarget == otherMessage.hasTarget &&
      (!self.hasTarget || [self.target isEqual:otherMessage.target]) &&
      self.hasLicenseId == otherMessage.hasLicenseId &&
      (!self.hasLicenseId || [self.licenseId isEqual:otherMessage.licenseId]) &&
      self.hasCreated == otherMessage.hasCreated &&
      (!self.hasCreated || self.created == otherMessage.created) &&
      self.hasAdditional == otherMessage.hasAdditional &&
      (!self.hasAdditional || [self.additional isEqual:otherMessage.additional]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  if (self.hasTarget) {
    hashCode = hashCode * 31 + [self.target hash];
  }
  if (self.hasLicenseId) {
    hashCode = hashCode * 31 + [self.licenseId hash];
  }
  if (self.hasCreated) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.created] hash];
  }
  if (self.hasAdditional) {
    hashCode = hashCode * 31 + [self.additional hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FPMetadataBuilder()
@property (strong) FPMetadata* resultMetadata;
@end

@implementation FPMetadataBuilder
@synthesize resultMetadata;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultMetadata = [[FPMetadata alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultMetadata;
}
- (FPMetadataBuilder*) clear {
  self.resultMetadata = [[FPMetadata alloc] init];
  return self;
}
- (FPMetadataBuilder*) clone {
  return [FPMetadata builderWithPrototype:resultMetadata];
}
- (FPMetadata*) defaultInstance {
  return [FPMetadata defaultInstance];
}
- (FPMetadata*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FPMetadata*) buildPartial {
  FPMetadata* returnMe = resultMetadata;
  self.resultMetadata = nil;
  return returnMe;
}
- (FPMetadataBuilder*) mergeFrom:(FPMetadata*) other {
  if (other == [FPMetadata defaultInstance]) {
    return self;
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasTarget) {
    [self setTarget:other.target];
  }
  if (other.hasLicenseId) {
    [self setLicenseId:other.licenseId];
  }
  if (other.hasCreated) {
    [self setCreated:other.created];
  }
  if (other.hasAdditional) {
    [self setAdditional:other.additional];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FPMetadataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FPMetadataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setName:[input readString]];
        break;
      }
      case 18: {
        [self setTarget:[input readString]];
        break;
      }
      case 26: {
        [self setLicenseId:[input readString]];
        break;
      }
      case 32: {
        [self setCreated:[input readInt64]];
        break;
      }
      case 42: {
        [self setAdditional:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasName {
  return resultMetadata.hasName;
}
- (NSString*) name {
  return resultMetadata.name;
}
- (FPMetadataBuilder*) setName:(NSString*) value {
  resultMetadata.hasName = YES;
  resultMetadata.name = value;
  return self;
}
- (FPMetadataBuilder*) clearName {
  resultMetadata.hasName = NO;
  resultMetadata.name = @"";
  return self;
}
- (BOOL) hasTarget {
  return resultMetadata.hasTarget;
}
- (NSString*) target {
  return resultMetadata.target;
}
- (FPMetadataBuilder*) setTarget:(NSString*) value {
  resultMetadata.hasTarget = YES;
  resultMetadata.target = value;
  return self;
}
- (FPMetadataBuilder*) clearTarget {
  resultMetadata.hasTarget = NO;
  resultMetadata.target = @"";
  return self;
}
- (BOOL) hasLicenseId {
  return resultMetadata.hasLicenseId;
}
- (NSString*) licenseId {
  return resultMetadata.licenseId;
}
- (FPMetadataBuilder*) setLicenseId:(NSString*) value {
  resultMetadata.hasLicenseId = YES;
  resultMetadata.licenseId = value;
  return self;
}
- (FPMetadataBuilder*) clearLicenseId {
  resultMetadata.hasLicenseId = NO;
  resultMetadata.licenseId = @"";
  return self;
}
- (BOOL) hasCreated {
  return resultMetadata.hasCreated;
}
- (SInt64) created {
  return resultMetadata.created;
}
- (FPMetadataBuilder*) setCreated:(SInt64) value {
  resultMetadata.hasCreated = YES;
  resultMetadata.created = value;
  return self;
}
- (FPMetadataBuilder*) clearCreated {
  resultMetadata.hasCreated = NO;
  resultMetadata.created = 0L;
  return self;
}
- (BOOL) hasAdditional {
  return resultMetadata.hasAdditional;
}
- (NSData*) additional {
  return resultMetadata.additional;
}
- (FPMetadataBuilder*) setAdditional:(NSData*) value {
  resultMetadata.hasAdditional = YES;
  resultMetadata.additional = value;
  return self;
}
- (FPMetadataBuilder*) clearAdditional {
  resultMetadata.hasAdditional = NO;
  resultMetadata.additional = [NSData data];
  return self;
}
@end

@interface FPLicense ()
@property (strong) FPMetadata* license;
@property (strong) NSData* signature;
@end

@implementation FPLicense

- (BOOL) hasLicense {
  return !!hasLicense_;
}
- (void) setHasLicense:(BOOL) _value_ {
  hasLicense_ = !!_value_;
}
@synthesize license;
- (BOOL) hasSignature {
  return !!hasSignature_;
}
- (void) setHasSignature:(BOOL) _value_ {
  hasSignature_ = !!_value_;
}
@synthesize signature;
- (instancetype) init {
  if ((self = [super init])) {
    self.license = [FPMetadata defaultInstance];
    self.signature = [NSData data];
  }
  return self;
}
static FPLicense* defaultFPLicenseInstance = nil;
+ (void) initialize {
  if (self == [FPLicense class]) {
    defaultFPLicenseInstance = [[FPLicense alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFPLicenseInstance;
}
- (instancetype) defaultInstance {
  return defaultFPLicenseInstance;
}
- (BOOL) isInitialized {
  if (!self.hasLicense) {
    return NO;
  }
  if (!self.hasSignature) {
    return NO;
  }
  if (!self.license.isInitialized) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasLicense) {
    [output writeMessage:1 value:self.license];
  }
  if (self.hasSignature) {
    [output writeData:6 value:self.signature];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasLicense) {
    size_ += computeMessageSize(1, self.license);
  }
  if (self.hasSignature) {
    size_ += computeDataSize(6, self.signature);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FPLicense*) parseFromData:(NSData*) data {
  return (FPLicense*)[[[FPLicense builder] mergeFromData:data] build];
}
+ (FPLicense*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPLicense*)[[[FPLicense builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FPLicense*) parseFromInputStream:(NSInputStream*) input {
  return (FPLicense*)[[[FPLicense builder] mergeFromInputStream:input] build];
}
+ (FPLicense*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPLicense*)[[[FPLicense builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FPLicense*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FPLicense*)[[[FPLicense builder] mergeFromCodedInputStream:input] build];
}
+ (FPLicense*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPLicense*)[[[FPLicense builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FPLicenseBuilder*) builder {
  return [[FPLicenseBuilder alloc] init];
}
+ (FPLicenseBuilder*) builderWithPrototype:(FPLicense*) prototype {
  return [[FPLicense builder] mergeFrom:prototype];
}
- (FPLicenseBuilder*) builder {
  return [FPLicense builder];
}
- (FPLicenseBuilder*) toBuilder {
  return [FPLicense builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasLicense) {
    [output appendFormat:@"%@%@ {\n", indent, @"license"];
    [self.license writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasSignature) {
    [output appendFormat:@"%@%@: %@\n", indent, @"signature", self.signature];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasLicense) {
   NSMutableDictionary *messageDictionary = [NSMutableDictionary dictionary]; 
   [self.license storeInDictionary:messageDictionary];
   [dictionary setObject:[NSDictionary dictionaryWithDictionary:messageDictionary] forKey:@"license"];
  }
  if (self.hasSignature) {
    [dictionary setObject: self.signature forKey: @"signature"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FPLicense class]]) {
    return NO;
  }
  FPLicense *otherMessage = other;
  return
      self.hasLicense == otherMessage.hasLicense &&
      (!self.hasLicense || [self.license isEqual:otherMessage.license]) &&
      self.hasSignature == otherMessage.hasSignature &&
      (!self.hasSignature || [self.signature isEqual:otherMessage.signature]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasLicense) {
    hashCode = hashCode * 31 + [self.license hash];
  }
  if (self.hasSignature) {
    hashCode = hashCode * 31 + [self.signature hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FPLicenseBuilder()
@property (strong) FPLicense* resultLicense;
@end

@implementation FPLicenseBuilder
@synthesize resultLicense;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultLicense = [[FPLicense alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultLicense;
}
- (FPLicenseBuilder*) clear {
  self.resultLicense = [[FPLicense alloc] init];
  return self;
}
- (FPLicenseBuilder*) clone {
  return [FPLicense builderWithPrototype:resultLicense];
}
- (FPLicense*) defaultInstance {
  return [FPLicense defaultInstance];
}
- (FPLicense*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FPLicense*) buildPartial {
  FPLicense* returnMe = resultLicense;
  self.resultLicense = nil;
  return returnMe;
}
- (FPLicenseBuilder*) mergeFrom:(FPLicense*) other {
  if (other == [FPLicense defaultInstance]) {
    return self;
  }
  if (other.hasLicense) {
    [self mergeLicense:other.license];
  }
  if (other.hasSignature) {
    [self setSignature:other.signature];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FPLicenseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FPLicenseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        FPMetadataBuilder* subBuilder = [FPMetadata builder];
        if (self.hasLicense) {
          [subBuilder mergeFrom:self.license];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setLicense:[subBuilder buildPartial]];
        break;
      }
      case 50: {
        [self setSignature:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasLicense {
  return resultLicense.hasLicense;
}
- (FPMetadata*) license {
  return resultLicense.license;
}
- (FPLicenseBuilder*) setLicense:(FPMetadata*) value {
  resultLicense.hasLicense = YES;
  resultLicense.license = value;
  return self;
}
- (FPLicenseBuilder*) setLicenseBuilder:(FPMetadataBuilder*) builderForValue {
  return [self setLicense:[builderForValue build]];
}
- (FPLicenseBuilder*) mergeLicense:(FPMetadata*) value {
  if (resultLicense.hasLicense &&
      resultLicense.license != [FPMetadata defaultInstance]) {
    resultLicense.license =
      [[[FPMetadata builderWithPrototype:resultLicense.license] mergeFrom:value] buildPartial];
  } else {
    resultLicense.license = value;
  }
  resultLicense.hasLicense = YES;
  return self;
}
- (FPLicenseBuilder*) clearLicense {
  resultLicense.hasLicense = NO;
  resultLicense.license = [FPMetadata defaultInstance];
  return self;
}
- (BOOL) hasSignature {
  return resultLicense.hasSignature;
}
- (NSData*) signature {
  return resultLicense.signature;
}
- (FPLicenseBuilder*) setSignature:(NSData*) value {
  resultLicense.hasSignature = YES;
  resultLicense.signature = value;
  return self;
}
- (FPLicenseBuilder*) clearSignature {
  resultLicense.hasSignature = NO;
  resultLicense.signature = [NSData data];
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
