// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "License.pb.h"
// @@protoc_insertion_point(imports)

@implementation FPLicenseRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [FPLicenseRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [ObjectivecDescriptorRoot registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface FPLicense ()
@property (strong) FPLicenseMetadata* license;
@property (strong) NSData* signature;
@end

@implementation FPLicense

- (BOOL) hasLicense {
  return !!hasLicense_;
}
- (void) setHasLicense:(BOOL) _value_ {
  hasLicense_ = !!_value_;
}
@synthesize license;
- (BOOL) hasSignature {
  return !!hasSignature_;
}
- (void) setHasSignature:(BOOL) _value_ {
  hasSignature_ = !!_value_;
}
@synthesize signature;
- (instancetype) init {
  if ((self = [super init])) {
    self.license = [FPLicenseMetadata defaultInstance];
    self.signature = [NSData data];
  }
  return self;
}
static FPLicense* defaultFPLicenseInstance = nil;
+ (void) initialize {
  if (self == [FPLicense class]) {
    defaultFPLicenseInstance = [[FPLicense alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFPLicenseInstance;
}
- (instancetype) defaultInstance {
  return defaultFPLicenseInstance;
}
- (BOOL) isInitialized {
  if (!self.hasLicense) {
    return NO;
  }
  if (!self.hasSignature) {
    return NO;
  }
  if (!self.license.isInitialized) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasLicense) {
    [output writeMessage:1 value:self.license];
  }
  if (self.hasSignature) {
    [output writeData:9 value:self.signature];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasLicense) {
    size_ += computeMessageSize(1, self.license);
  }
  if (self.hasSignature) {
    size_ += computeDataSize(9, self.signature);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FPLicense*) parseFromData:(NSData*) data {
  return (FPLicense*)[[[FPLicense builder] mergeFromData:data] build];
}
+ (FPLicense*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPLicense*)[[[FPLicense builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FPLicense*) parseFromInputStream:(NSInputStream*) input {
  return (FPLicense*)[[[FPLicense builder] mergeFromInputStream:input] build];
}
+ (FPLicense*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPLicense*)[[[FPLicense builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FPLicense*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FPLicense*)[[[FPLicense builder] mergeFromCodedInputStream:input] build];
}
+ (FPLicense*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPLicense*)[[[FPLicense builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FPLicenseBuilder*) builder {
  return [[FPLicenseBuilder alloc] init];
}
+ (FPLicenseBuilder*) builderWithPrototype:(FPLicense*) prototype {
  return [[FPLicense builder] mergeFrom:prototype];
}
- (FPLicenseBuilder*) builder {
  return [FPLicense builder];
}
- (FPLicenseBuilder*) toBuilder {
  return [FPLicense builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasLicense) {
    [output appendFormat:@"%@%@ {\n", indent, @"license"];
    [self.license writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasSignature) {
    [output appendFormat:@"%@%@: %@\n", indent, @"signature", self.signature];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasLicense) {
   NSMutableDictionary *messageDictionary = [NSMutableDictionary dictionary]; 
   [self.license storeInDictionary:messageDictionary];
   [dictionary setObject:[NSDictionary dictionaryWithDictionary:messageDictionary] forKey:@"license"];
  }
  if (self.hasSignature) {
    [dictionary setObject: self.signature forKey: @"signature"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FPLicense class]]) {
    return NO;
  }
  FPLicense *otherMessage = other;
  return
      self.hasLicense == otherMessage.hasLicense &&
      (!self.hasLicense || [self.license isEqual:otherMessage.license]) &&
      self.hasSignature == otherMessage.hasSignature &&
      (!self.hasSignature || [self.signature isEqual:otherMessage.signature]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasLicense) {
    hashCode = hashCode * 31 + [self.license hash];
  }
  if (self.hasSignature) {
    hashCode = hashCode * 31 + [self.signature hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FPLicenseMetadata ()
@property (strong) NSString* name;
@property (strong) NSString* target;
@property (strong) NSString* licenseId;
@property SInt64 created;
@property (strong) NSString* email;
@property (strong) NSString* company;
@property SInt32 instances;
@property (strong) NSString* orderId;
@end

@implementation FPLicenseMetadata

- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) _value_ {
  hasName_ = !!_value_;
}
@synthesize name;
- (BOOL) hasTarget {
  return !!hasTarget_;
}
- (void) setHasTarget:(BOOL) _value_ {
  hasTarget_ = !!_value_;
}
@synthesize target;
- (BOOL) hasLicenseId {
  return !!hasLicenseId_;
}
- (void) setHasLicenseId:(BOOL) _value_ {
  hasLicenseId_ = !!_value_;
}
@synthesize licenseId;
- (BOOL) hasCreated {
  return !!hasCreated_;
}
- (void) setHasCreated:(BOOL) _value_ {
  hasCreated_ = !!_value_;
}
@synthesize created;
- (BOOL) hasEmail {
  return !!hasEmail_;
}
- (void) setHasEmail:(BOOL) _value_ {
  hasEmail_ = !!_value_;
}
@synthesize email;
- (BOOL) hasCompany {
  return !!hasCompany_;
}
- (void) setHasCompany:(BOOL) _value_ {
  hasCompany_ = !!_value_;
}
@synthesize company;
- (BOOL) hasInstances {
  return !!hasInstances_;
}
- (void) setHasInstances:(BOOL) _value_ {
  hasInstances_ = !!_value_;
}
@synthesize instances;
- (BOOL) hasOrderId {
  return !!hasOrderId_;
}
- (void) setHasOrderId:(BOOL) _value_ {
  hasOrderId_ = !!_value_;
}
@synthesize orderId;
- (instancetype) init {
  if ((self = [super init])) {
    self.name = @"";
    self.target = @"";
    self.licenseId = @"";
    self.created = 0L;
    self.email = @"";
    self.company = @"";
    self.instances = 0;
    self.orderId = @"";
  }
  return self;
}
static FPLicenseMetadata* defaultFPLicenseMetadataInstance = nil;
+ (void) initialize {
  if (self == [FPLicenseMetadata class]) {
    defaultFPLicenseMetadataInstance = [[FPLicenseMetadata alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFPLicenseMetadataInstance;
}
- (instancetype) defaultInstance {
  return defaultFPLicenseMetadataInstance;
}
- (BOOL) isInitialized {
  if (!self.hasName) {
    return NO;
  }
  if (!self.hasTarget) {
    return NO;
  }
  if (!self.hasLicenseId) {
    return NO;
  }
  if (!self.hasCreated) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasName) {
    [output writeString:1 value:self.name];
  }
  if (self.hasTarget) {
    [output writeString:2 value:self.target];
  }
  if (self.hasLicenseId) {
    [output writeString:3 value:self.licenseId];
  }
  if (self.hasCreated) {
    [output writeInt64:4 value:self.created];
  }
  if (self.hasEmail) {
    [output writeString:5 value:self.email];
  }
  if (self.hasCompany) {
    [output writeString:6 value:self.company];
  }
  if (self.hasInstances) {
    [output writeInt32:7 value:self.instances];
  }
  if (self.hasOrderId) {
    [output writeString:8 value:self.orderId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasName) {
    size_ += computeStringSize(1, self.name);
  }
  if (self.hasTarget) {
    size_ += computeStringSize(2, self.target);
  }
  if (self.hasLicenseId) {
    size_ += computeStringSize(3, self.licenseId);
  }
  if (self.hasCreated) {
    size_ += computeInt64Size(4, self.created);
  }
  if (self.hasEmail) {
    size_ += computeStringSize(5, self.email);
  }
  if (self.hasCompany) {
    size_ += computeStringSize(6, self.company);
  }
  if (self.hasInstances) {
    size_ += computeInt32Size(7, self.instances);
  }
  if (self.hasOrderId) {
    size_ += computeStringSize(8, self.orderId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FPLicenseMetadata*) parseFromData:(NSData*) data {
  return (FPLicenseMetadata*)[[[FPLicenseMetadata builder] mergeFromData:data] build];
}
+ (FPLicenseMetadata*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPLicenseMetadata*)[[[FPLicenseMetadata builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FPLicenseMetadata*) parseFromInputStream:(NSInputStream*) input {
  return (FPLicenseMetadata*)[[[FPLicenseMetadata builder] mergeFromInputStream:input] build];
}
+ (FPLicenseMetadata*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPLicenseMetadata*)[[[FPLicenseMetadata builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FPLicenseMetadata*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FPLicenseMetadata*)[[[FPLicenseMetadata builder] mergeFromCodedInputStream:input] build];
}
+ (FPLicenseMetadata*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FPLicenseMetadata*)[[[FPLicenseMetadata builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FPLicenseMetadataBuilder*) builder {
  return [[FPLicenseMetadataBuilder alloc] init];
}
+ (FPLicenseMetadataBuilder*) builderWithPrototype:(FPLicenseMetadata*) prototype {
  return [[FPLicenseMetadata builder] mergeFrom:prototype];
}
- (FPLicenseMetadataBuilder*) builder {
  return [FPLicenseMetadata builder];
}
- (FPLicenseMetadataBuilder*) toBuilder {
  return [FPLicenseMetadata builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  if (self.hasTarget) {
    [output appendFormat:@"%@%@: %@\n", indent, @"target", self.target];
  }
  if (self.hasLicenseId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"licenseId", self.licenseId];
  }
  if (self.hasCreated) {
    [output appendFormat:@"%@%@: %@\n", indent, @"created", [NSNumber numberWithLongLong:self.created]];
  }
  if (self.hasEmail) {
    [output appendFormat:@"%@%@: %@\n", indent, @"email", self.email];
  }
  if (self.hasCompany) {
    [output appendFormat:@"%@%@: %@\n", indent, @"company", self.company];
  }
  if (self.hasInstances) {
    [output appendFormat:@"%@%@: %@\n", indent, @"instances", [NSNumber numberWithInteger:self.instances]];
  }
  if (self.hasOrderId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"orderId", self.orderId];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasName) {
    [dictionary setObject: self.name forKey: @"name"];
  }
  if (self.hasTarget) {
    [dictionary setObject: self.target forKey: @"target"];
  }
  if (self.hasLicenseId) {
    [dictionary setObject: self.licenseId forKey: @"licenseId"];
  }
  if (self.hasCreated) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.created] forKey: @"created"];
  }
  if (self.hasEmail) {
    [dictionary setObject: self.email forKey: @"email"];
  }
  if (self.hasCompany) {
    [dictionary setObject: self.company forKey: @"company"];
  }
  if (self.hasInstances) {
    [dictionary setObject: [NSNumber numberWithInteger:self.instances] forKey: @"instances"];
  }
  if (self.hasOrderId) {
    [dictionary setObject: self.orderId forKey: @"orderId"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FPLicenseMetadata class]]) {
    return NO;
  }
  FPLicenseMetadata *otherMessage = other;
  return
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      self.hasTarget == otherMessage.hasTarget &&
      (!self.hasTarget || [self.target isEqual:otherMessage.target]) &&
      self.hasLicenseId == otherMessage.hasLicenseId &&
      (!self.hasLicenseId || [self.licenseId isEqual:otherMessage.licenseId]) &&
      self.hasCreated == otherMessage.hasCreated &&
      (!self.hasCreated || self.created == otherMessage.created) &&
      self.hasEmail == otherMessage.hasEmail &&
      (!self.hasEmail || [self.email isEqual:otherMessage.email]) &&
      self.hasCompany == otherMessage.hasCompany &&
      (!self.hasCompany || [self.company isEqual:otherMessage.company]) &&
      self.hasInstances == otherMessage.hasInstances &&
      (!self.hasInstances || self.instances == otherMessage.instances) &&
      self.hasOrderId == otherMessage.hasOrderId &&
      (!self.hasOrderId || [self.orderId isEqual:otherMessage.orderId]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  if (self.hasTarget) {
    hashCode = hashCode * 31 + [self.target hash];
  }
  if (self.hasLicenseId) {
    hashCode = hashCode * 31 + [self.licenseId hash];
  }
  if (self.hasCreated) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.created] hash];
  }
  if (self.hasEmail) {
    hashCode = hashCode * 31 + [self.email hash];
  }
  if (self.hasCompany) {
    hashCode = hashCode * 31 + [self.company hash];
  }
  if (self.hasInstances) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.instances] hash];
  }
  if (self.hasOrderId) {
    hashCode = hashCode * 31 + [self.orderId hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FPLicenseMetadataBuilder()
@property (strong) FPLicenseMetadata* resultMetadata;
@end

@implementation FPLicenseMetadataBuilder
@synthesize resultMetadata;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultMetadata = [[FPLicenseMetadata alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultMetadata;
}
- (FPLicenseMetadataBuilder*) clear {
  self.resultMetadata = [[FPLicenseMetadata alloc] init];
  return self;
}
- (FPLicenseMetadataBuilder*) clone {
  return [FPLicenseMetadata builderWithPrototype:resultMetadata];
}
- (FPLicenseMetadata*) defaultInstance {
  return [FPLicenseMetadata defaultInstance];
}
- (FPLicenseMetadata*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FPLicenseMetadata*) buildPartial {
  FPLicenseMetadata* returnMe = resultMetadata;
  self.resultMetadata = nil;
  return returnMe;
}
- (FPLicenseMetadataBuilder*) mergeFrom:(FPLicenseMetadata*) other {
  if (other == [FPLicenseMetadata defaultInstance]) {
    return self;
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasTarget) {
    [self setTarget:other.target];
  }
  if (other.hasLicenseId) {
    [self setLicenseId:other.licenseId];
  }
  if (other.hasCreated) {
    [self setCreated:other.created];
  }
  if (other.hasEmail) {
    [self setEmail:other.email];
  }
  if (other.hasCompany) {
    [self setCompany:other.company];
  }
  if (other.hasInstances) {
    [self setInstances:other.instances];
  }
  if (other.hasOrderId) {
    [self setOrderId:other.orderId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FPLicenseMetadataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FPLicenseMetadataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setName:[input readString]];
        break;
      }
      case 18: {
        [self setTarget:[input readString]];
        break;
      }
      case 26: {
        [self setLicenseId:[input readString]];
        break;
      }
      case 32: {
        [self setCreated:[input readInt64]];
        break;
      }
      case 42: {
        [self setEmail:[input readString]];
        break;
      }
      case 50: {
        [self setCompany:[input readString]];
        break;
      }
      case 56: {
        [self setInstances:[input readInt32]];
        break;
      }
      case 66: {
        [self setOrderId:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasName {
  return resultMetadata.hasName;
}
- (NSString*) name {
  return resultMetadata.name;
}
- (FPLicenseMetadataBuilder*) setName:(NSString*) value {
  resultMetadata.hasName = YES;
  resultMetadata.name = value;
  return self;
}
- (FPLicenseMetadataBuilder*) clearName {
  resultMetadata.hasName = NO;
  resultMetadata.name = @"";
  return self;
}
- (BOOL) hasTarget {
  return resultMetadata.hasTarget;
}
- (NSString*) target {
  return resultMetadata.target;
}
- (FPLicenseMetadataBuilder*) setTarget:(NSString*) value {
  resultMetadata.hasTarget = YES;
  resultMetadata.target = value;
  return self;
}
- (FPLicenseMetadataBuilder*) clearTarget {
  resultMetadata.hasTarget = NO;
  resultMetadata.target = @"";
  return self;
}
- (BOOL) hasLicenseId {
  return resultMetadata.hasLicenseId;
}
- (NSString*) licenseId {
  return resultMetadata.licenseId;
}
- (FPLicenseMetadataBuilder*) setLicenseId:(NSString*) value {
  resultMetadata.hasLicenseId = YES;
  resultMetadata.licenseId = value;
  return self;
}
- (FPLicenseMetadataBuilder*) clearLicenseId {
  resultMetadata.hasLicenseId = NO;
  resultMetadata.licenseId = @"";
  return self;
}
- (BOOL) hasCreated {
  return resultMetadata.hasCreated;
}
- (SInt64) created {
  return resultMetadata.created;
}
- (FPLicenseMetadataBuilder*) setCreated:(SInt64) value {
  resultMetadata.hasCreated = YES;
  resultMetadata.created = value;
  return self;
}
- (FPLicenseMetadataBuilder*) clearCreated {
  resultMetadata.hasCreated = NO;
  resultMetadata.created = 0L;
  return self;
}
- (BOOL) hasEmail {
  return resultMetadata.hasEmail;
}
- (NSString*) email {
  return resultMetadata.email;
}
- (FPLicenseMetadataBuilder*) setEmail:(NSString*) value {
  resultMetadata.hasEmail = YES;
  resultMetadata.email = value;
  return self;
}
- (FPLicenseMetadataBuilder*) clearEmail {
  resultMetadata.hasEmail = NO;
  resultMetadata.email = @"";
  return self;
}
- (BOOL) hasCompany {
  return resultMetadata.hasCompany;
}
- (NSString*) company {
  return resultMetadata.company;
}
- (FPLicenseMetadataBuilder*) setCompany:(NSString*) value {
  resultMetadata.hasCompany = YES;
  resultMetadata.company = value;
  return self;
}
- (FPLicenseMetadataBuilder*) clearCompany {
  resultMetadata.hasCompany = NO;
  resultMetadata.company = @"";
  return self;
}
- (BOOL) hasInstances {
  return resultMetadata.hasInstances;
}
- (SInt32) instances {
  return resultMetadata.instances;
}
- (FPLicenseMetadataBuilder*) setInstances:(SInt32) value {
  resultMetadata.hasInstances = YES;
  resultMetadata.instances = value;
  return self;
}
- (FPLicenseMetadataBuilder*) clearInstances {
  resultMetadata.hasInstances = NO;
  resultMetadata.instances = 0;
  return self;
}
- (BOOL) hasOrderId {
  return resultMetadata.hasOrderId;
}
- (NSString*) orderId {
  return resultMetadata.orderId;
}
- (FPLicenseMetadataBuilder*) setOrderId:(NSString*) value {
  resultMetadata.hasOrderId = YES;
  resultMetadata.orderId = value;
  return self;
}
- (FPLicenseMetadataBuilder*) clearOrderId {
  resultMetadata.hasOrderId = NO;
  resultMetadata.orderId = @"";
  return self;
}
@end

@interface FPLicenseBuilder()
@property (strong) FPLicense* resultLicense;
@end

@implementation FPLicenseBuilder
@synthesize resultLicense;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultLicense = [[FPLicense alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultLicense;
}
- (FPLicenseBuilder*) clear {
  self.resultLicense = [[FPLicense alloc] init];
  return self;
}
- (FPLicenseBuilder*) clone {
  return [FPLicense builderWithPrototype:resultLicense];
}
- (FPLicense*) defaultInstance {
  return [FPLicense defaultInstance];
}
- (FPLicense*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FPLicense*) buildPartial {
  FPLicense* returnMe = resultLicense;
  self.resultLicense = nil;
  return returnMe;
}
- (FPLicenseBuilder*) mergeFrom:(FPLicense*) other {
  if (other == [FPLicense defaultInstance]) {
    return self;
  }
  if (other.hasLicense) {
    [self mergeLicense:other.license];
  }
  if (other.hasSignature) {
    [self setSignature:other.signature];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FPLicenseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FPLicenseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        FPLicenseMetadataBuilder* subBuilder = [FPLicenseMetadata builder];
        if (self.hasLicense) {
          [subBuilder mergeFrom:self.license];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setLicense:[subBuilder buildPartial]];
        break;
      }
      case 74: {
        [self setSignature:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasLicense {
  return resultLicense.hasLicense;
}
- (FPLicenseMetadata*) license {
  return resultLicense.license;
}
- (FPLicenseBuilder*) setLicense:(FPLicenseMetadata*) value {
  resultLicense.hasLicense = YES;
  resultLicense.license = value;
  return self;
}
- (FPLicenseBuilder*) setLicenseBuilder:(FPLicenseMetadataBuilder*) builderForValue {
  return [self setLicense:[builderForValue build]];
}
- (FPLicenseBuilder*) mergeLicense:(FPLicenseMetadata*) value {
  if (resultLicense.hasLicense &&
      resultLicense.license != [FPLicenseMetadata defaultInstance]) {
    resultLicense.license =
      [[[FPLicenseMetadata builderWithPrototype:resultLicense.license] mergeFrom:value] buildPartial];
  } else {
    resultLicense.license = value;
  }
  resultLicense.hasLicense = YES;
  return self;
}
- (FPLicenseBuilder*) clearLicense {
  resultLicense.hasLicense = NO;
  resultLicense.license = [FPLicenseMetadata defaultInstance];
  return self;
}
- (BOOL) hasSignature {
  return resultLicense.hasSignature;
}
- (NSData*) signature {
  return resultLicense.signature;
}
- (FPLicenseBuilder*) setSignature:(NSData*) value {
  resultLicense.hasSignature = YES;
  resultLicense.signature = value;
  return self;
}
- (FPLicenseBuilder*) clearSignature {
  resultLicense.hasSignature = NO;
  resultLicense.signature = [NSData data];
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
