// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class FPLicense;
@class FPLicenseBuilder;
@class FPLicenseMetadata;
@class FPLicenseMetadataBuilder;
@class ObjectiveCFileOptions;
@class ObjectiveCFileOptionsBuilder;
@class PBDescriptorProto;
@class PBDescriptorProtoBuilder;
@class PBDescriptorProtoExtensionRange;
@class PBDescriptorProtoExtensionRangeBuilder;
@class PBDescriptorProtoReservedRange;
@class PBDescriptorProtoReservedRangeBuilder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProtoBuilder;
@class PBEnumOptions;
@class PBEnumOptionsBuilder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProtoBuilder;
@class PBEnumValueOptions;
@class PBEnumValueOptionsBuilder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProtoBuilder;
@class PBFieldOptions;
@class PBFieldOptionsBuilder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProtoBuilder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSetBuilder;
@class PBFileOptions;
@class PBFileOptionsBuilder;
@class PBMessageOptions;
@class PBMessageOptionsBuilder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProtoBuilder;
@class PBMethodOptions;
@class PBMethodOptionsBuilder;
@class PBOneofDescriptorProto;
@class PBOneofDescriptorProtoBuilder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProtoBuilder;
@class PBServiceOptions;
@class PBServiceOptionsBuilder;
@class PBSourceCodeInfo;
@class PBSourceCodeInfoBuilder;
@class PBSourceCodeInfoLocation;
@class PBSourceCodeInfoLocationBuilder;
@class PBUninterpretedOption;
@class PBUninterpretedOptionBuilder;
@class PBUninterpretedOptionNamePart;
@class PBUninterpretedOptionNamePartBuilder;



@interface FPLicenseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define License_license @"license"
#define License_signature @"signature"
@interface FPLicense : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLicense_:1;
  BOOL hasSignature_:1;
  FPLicenseMetadata* license;
  NSData* signature;
}
- (BOOL) hasLicense;
- (BOOL) hasSignature;
@property (readonly, strong) FPLicenseMetadata* license;
@property (readonly, strong) NSData* signature;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FPLicenseBuilder*) builder;
+ (FPLicenseBuilder*) builder;
+ (FPLicenseBuilder*) builderWithPrototype:(FPLicense*) prototype;
- (FPLicenseBuilder*) toBuilder;

+ (FPLicense*) parseFromData:(NSData*) data;
+ (FPLicense*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FPLicense*) parseFromInputStream:(NSInputStream*) input;
+ (FPLicense*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FPLicense*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FPLicense*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define Metadata_name @"name"
#define Metadata_target @"target"
#define Metadata_licenseId @"licenseId"
#define Metadata_created @"created"
#define Metadata_email @"email"
#define Metadata_company @"company"
#define Metadata_instances @"instances"
#define Metadata_orderId @"orderId"
@interface FPLicenseMetadata : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCreated_:1;
  BOOL hasInstances_:1;
  BOOL hasName_:1;
  BOOL hasTarget_:1;
  BOOL hasLicenseId_:1;
  BOOL hasEmail_:1;
  BOOL hasCompany_:1;
  BOOL hasOrderId_:1;
  SInt64 created;
  SInt32 instances;
  NSString* name;
  NSString* target;
  NSString* licenseId;
  NSString* email;
  NSString* company;
  NSString* orderId;
}
- (BOOL) hasName;
- (BOOL) hasTarget;
- (BOOL) hasLicenseId;
- (BOOL) hasCreated;
- (BOOL) hasEmail;
- (BOOL) hasCompany;
- (BOOL) hasInstances;
- (BOOL) hasOrderId;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* target;
@property (readonly, strong) NSString* licenseId;
@property (readonly) SInt64 created;
@property (readonly, strong) NSString* email;
@property (readonly, strong) NSString* company;
@property (readonly) SInt32 instances;
@property (readonly, strong) NSString* orderId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FPLicenseMetadataBuilder*) builder;
+ (FPLicenseMetadataBuilder*) builder;
+ (FPLicenseMetadataBuilder*) builderWithPrototype:(FPLicenseMetadata*) prototype;
- (FPLicenseMetadataBuilder*) toBuilder;

+ (FPLicenseMetadata*) parseFromData:(NSData*) data;
+ (FPLicenseMetadata*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FPLicenseMetadata*) parseFromInputStream:(NSInputStream*) input;
+ (FPLicenseMetadata*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FPLicenseMetadata*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FPLicenseMetadata*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FPLicenseMetadataBuilder : PBGeneratedMessageBuilder {
@private
  FPLicenseMetadata* resultMetadata;
}

- (FPLicenseMetadata*) defaultInstance;

- (FPLicenseMetadataBuilder*) clear;
- (FPLicenseMetadataBuilder*) clone;

- (FPLicenseMetadata*) build;
- (FPLicenseMetadata*) buildPartial;

- (FPLicenseMetadataBuilder*) mergeFrom:(FPLicenseMetadata*) other;
- (FPLicenseMetadataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FPLicenseMetadataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (FPLicenseMetadataBuilder*) setName:(NSString*) value;
- (FPLicenseMetadataBuilder*) clearName;

- (BOOL) hasTarget;
- (NSString*) target;
- (FPLicenseMetadataBuilder*) setTarget:(NSString*) value;
- (FPLicenseMetadataBuilder*) clearTarget;

- (BOOL) hasLicenseId;
- (NSString*) licenseId;
- (FPLicenseMetadataBuilder*) setLicenseId:(NSString*) value;
- (FPLicenseMetadataBuilder*) clearLicenseId;

- (BOOL) hasCreated;
- (SInt64) created;
- (FPLicenseMetadataBuilder*) setCreated:(SInt64) value;
- (FPLicenseMetadataBuilder*) clearCreated;

- (BOOL) hasEmail;
- (NSString*) email;
- (FPLicenseMetadataBuilder*) setEmail:(NSString*) value;
- (FPLicenseMetadataBuilder*) clearEmail;

- (BOOL) hasCompany;
- (NSString*) company;
- (FPLicenseMetadataBuilder*) setCompany:(NSString*) value;
- (FPLicenseMetadataBuilder*) clearCompany;

- (BOOL) hasInstances;
- (SInt32) instances;
- (FPLicenseMetadataBuilder*) setInstances:(SInt32) value;
- (FPLicenseMetadataBuilder*) clearInstances;

- (BOOL) hasOrderId;
- (NSString*) orderId;
- (FPLicenseMetadataBuilder*) setOrderId:(NSString*) value;
- (FPLicenseMetadataBuilder*) clearOrderId;
@end

@interface FPLicenseBuilder : PBGeneratedMessageBuilder {
@private
  FPLicense* resultLicense;
}

- (FPLicense*) defaultInstance;

- (FPLicenseBuilder*) clear;
- (FPLicenseBuilder*) clone;

- (FPLicense*) build;
- (FPLicense*) buildPartial;

- (FPLicenseBuilder*) mergeFrom:(FPLicense*) other;
- (FPLicenseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FPLicenseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLicense;
- (FPLicenseMetadata*) license;
- (FPLicenseBuilder*) setLicense:(FPLicenseMetadata*) value;
- (FPLicenseBuilder*) setLicenseBuilder:(FPLicenseMetadataBuilder*) builderForValue;
- (FPLicenseBuilder*) mergeLicense:(FPLicenseMetadata*) value;
- (FPLicenseBuilder*) clearLicense;

- (BOOL) hasSignature;
- (NSData*) signature;
- (FPLicenseBuilder*) setSignature:(NSData*) value;
- (FPLicenseBuilder*) clearSignature;
@end


// @@protoc_insertion_point(global_scope)
